In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Load the data 
data=pd.read_csv('admission.csv')

In [3]:
X=data[['GRE Score','TOEFL Score','University Rating','SOP','LOR ','CGPA','Research']]
Y=data['Chance of Admit ']

In [4]:
#convert data into arrays 
x=np.array(X)
y=np.array(Y)
x,y

(array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
        [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
        [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
        ...,
        [330.  , 120.  ,   5.  , ...,   5.  ,   9.56,   1.  ],
        [312.  , 103.  ,   4.  , ...,   5.  ,   8.43,   0.  ],
        [327.  , 113.  ,   4.  , ...,   4.5 ,   9.04,   0.  ]]),
 array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
        0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
        0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
        0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
        0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
        0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
        0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
        0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
        0.64, 0

In [5]:
from sklearn.model_selection import train_test_split

In [17]:
#split the data into 8:2 ratio
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train.shape,y_test.shape

((400, 7), (100,))

In [13]:
from sklearn.linear_model import LinearRegression
#train the data 
reg=LinearRegression().fit(x_train,y_train)

In [14]:
reg

LinearRegression()

In [18]:
#Accuracy score
reg.score(x_train,y_train)

0.8320406523764272

In [10]:
y_predict=reg.predict(x_test)
print(pd.DataFrame({'y_test':y_test,'y_predict':y_predict}))

    y_test  y_predict
0     0.64   0.660625
1     0.85   0.834679
2     0.80   0.778032
3     0.91   0.880545
4     0.68   0.601266
..     ...        ...
95    0.95   0.942146
96    0.64   0.545430
97    0.53   0.536364
98    0.48   0.600390
99    0.64   0.615350

[100 rows x 2 columns]


In [22]:
y_train_predict=reg.predict(x_train)
pd.DataFrame({'y_train':y_train,'y_train_predict':y_train_predict})

y_train  y_train_predict
0       0.91         0.931224
1       0.72         0.725415
2       0.96         0.964505
3       0.67         0.620260
4       0.75         0.711521
..       ...              ...
395     0.62         0.596311
396     0.86         0.824908
397     0.45         0.497030
398     0.89         0.939878
399     0.86         0.849116

[400 rows x 2 columns]

In [11]:
reg.predict([[335,120,3,4.5,4,9.05,1]])

array([0.87163774])

In [23]:
from sklearn import metrics

In [24]:
print(metrics.mean_absolute_error(y_train,y_train_predict))
print(metrics.mean_squared_error(y_train,y_train_predict))
print(np.sqrt(metrics.mean_squared_error(y_train,y_train_predict)))

0.041551691305557935
0.003421180327780946
0.058490856787885626


In [25]:
print(metrics.r2_score(y_test, y_predict))
print(metrics.r2_score(y_train,y_train_predict))
print(reg.score(x,y))

0.7664048993199385
0.8320406523764272
0.8214677895961422
